### ISSUE TITLE
[Feature Request]: Chromium support

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [swoops/eval_villain#4]
It'd be amazing if this had chromium support, as most other hacking add-ons are made for chromium

**Comment by swoops** [comment]
> It'd be amazing if this had chromium support

I agree but Eval Villain relies on [contentScripts.register](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register) and there is no support for that API on chrome.

If chrome gets that API I will be happy to port Eval Villain over.

Without `contentScripts.register` there would be a race condition between Eval Villain loading the user config and the target website executing something bad. In short, Eval Villain would miss trivial findings. I think DOM Invader avoids this race somehow by requiring the entire browser be restarted every time a configuration option is changed.

Feel free to leave this issue open in case someone else has the same idea. If someone sees that `contentScripts.register` has been added to chrome ping me and I will do the porting.

**Comment by ItsIgnacioPortal** [comment]
Got it. I'll be using DOM Invader on Chromium. It's still good that a Firefox alternative exists
