### ISSUE TITLE
Cannot load add-on via Selenium

### ISSUE THREAD

**Issue by psiinon** [swoops/eval_villain#5]
Hiya 😁 
We've had a bug complaining that Eval Villain is no longer loaded when ZAP launches Firefox: https://github.com/zaproxy/zaproxy/issues/7878

Thanks to @willdurand we've found out its a bug in Selenium, which we're following up on.

But there is a work around: "it looks like the source manifest.json doesn't include browser_specific_settings, which means AMO sets it (yes, AMO slightly updates manifest.json files these days). I think the workaround is to update the manifest.json file and add applications.gecko.id, and then get that new version signed by AMO."

You ok doing this until selenium gets fixed?

**Comment by swoops** [comment]
Yeah, I can try to do that.

I removed those settings because AMO complained about them during the last release.. I should have a new version pushed in a couple hours. I think I am going to read up on it just a bit.

**Comment by thc202** [comment]
It's no longer necessary to do that, we are now able to install the current version. Thank you!

I think this can be closed now.

**Comment by swoops** [comment]
Cool, thanks for the heads up.
